[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | __pycache__
  | build
  | dist
  | conf.py
)/
'''
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.4"
version_files = [
    "pyproject.toml:version",
    "yodu/__init__.py"
]
